# Generated by Django 5.1.3 on 2026-02-13 21:31

from django.db import migrations

def create_categories(apps, schema_editor):
    Category = apps.get_model('expenses', 'Category')
    Category.objects.create(name="Income")
    Category.objects.create(name="Needs")
    Category.objects.create(name="Wants")
    Category.objects.create(name="Savings")


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [migrations.RunPython(create_categories),
    ]
