# Generated by Django 5.1.3 on 2026-02-16 22:00

from django.db import migrations

class Migration(migrations.Migration):
    dependencies = [
        ('expenses', '0002_load_initial_categories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Expense',
            new_name='Transaction',
        ),
    ]